### PR TITLE
debugcc static build fix

### PR DESCRIPTION
**Pull request by 99degree**
Fix statically compiled debugcc

### CODE REVIEW

**Review by lumag — CHANGES_REQUESTED** [review]
Please improve your commit by:
- Fixing the authorship as recorded by git. See `git config --global user.name` and `git config --global user.email`
- Adding the SoB to your commit message (`git commit -s`)
- Describing why do you need this change, what is wrong with the current approach.

**Comment by lumag** [comment]
@99degree could you please fix the pull request according to the comments in the previous message?

**Comment by 99degree** [comment]
plz take a look if this fits
https://github.com/99degree/debugcc/commit/f55dc40d3e40e519d61daf01905ffd1b93a0ccb1

**Comment by lumag** [comment]
@99degree please force-push your commit to the master branch, this way the PR will also be updated.

**Comment by MarijnS95** [comment]
Besides that, before you force-push @99degree note that the linked commit doesn't fix the third point brought up by @lumag, `Describing why do you need this change, what is wrong with the current approach.`.

**Review by lumag — APPROVED** [review]

**Review by MarijnS95 — APPROVED** [review]
Just want to say post-merge, the updated commit message looks perfect 👍

**Comment by MarijnS95** [comment]
Looking at https://mesonbuild.com/Build-targets.html though, it seems configuring a library to build statically is natively possible directly through meson without any compiler/linker flags if I'm not mistaken?

**Comment by lumag** [comment]
@MarijnS95 Here we have static executable, not a library.

**Pull request merged**
